In [1]:

!pip install mysql-connector-python pandas

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: pandas in c:\users\daram\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\daram\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\daram\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\daram\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\daram\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\daram\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   -- ------------------------------------- 1.0/16.5 MB 10.3 MB/s eta 0:00:02
   ------ --------------------------------- 2.6/16.5 MB 8.6 MB/s eta 0:00:02
   ---------- ----------------------------- 4.2/16.5 MB 8.3 MB/s eta 0:00:02
   ------------- -------------------------- 5.8/16.5 MB 8.0 MB/s eta 0:00:02
   ------------------ --------------------- 7.6/16.5 MB 8.2 MB/s eta 0:00:02
   ---------------------- ----------------- 9.4/16.5 MB 8.3 MB/s eta 0:00:01
   --------------------------- ------------ 11.5/16.5 MB 8.6 MB/s eta 0:00:01
   -------------------------------- ------- 13.4/16.5 MB 8.7 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 8.8 MB/s  0:00:01
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [2]:
import mysql.connector
import pandas as pd

In [5]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="3030",
    database="ecommerce_analytics"
)

In [6]:
connection.is_connected()

True

In [7]:
#customers

In [8]:
customers_df = pd.read_sql("SELECT * FROM customers", connection)
customers_df.head()

C:\Users\daram\AppData\Local\Temp\ipykernel_36516\849475264.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers_df = pd.read_sql("SELECT * FROM customers", connection)

,customer_id,customer_name,email,phone_number,location,registration_date
0,1,Kavya,kavya@gmail.com,9876543210,Hyderabad,2024-01-10
1,2,Ravi,ravi@gmail.com,9876543211,Chennai,2024-02-15
2,3,Meena,meena@gmail.com,9876543212,Bangalore,2024-03-01
3,4,Arjun,arjun@gmail.com,9876543213,Mumbai,2024-01-25
4,5,Sneha,sneha@gmail.com,9876543214,Delhi,2024-02-10

In [9]:
#products

In [10]:
products_df = pd.read_sql("SELECT * FROM products", connection)
products_df.head()

C:\Users\daram\AppData\Local\Temp\ipykernel_36516\1398855516.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products_df = pd.read_sql("SELECT * FROM products", connection)

   product_id   product_name     category    price
0         101          Kurti     Clothing   1200.0
1         102         Laptop  Electronics  55000.0
2         103       Lipstick       Beauty    700.0
3         104        Handbag  Accessories   2500.0
4         105  Mixer Grinder         Home   3500.0

In [11]:
#orders

In [12]:
orders_df = pd.read_sql("SELECT * FROM orders", connection)
orders_df.head()

C:\Users\daram\AppData\Local\Temp\ipykernel_36516\3456963410.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders_df = pd.read_sql("SELECT * FROM orders", connection)

   order_id  customer_id  order_date  total_amount
0       201            1  2024-04-01        1200.0
1       202            2  2024-04-03       55000.0
2       203            3  2024-04-04         700.0
3       204            4  2024-04-06        2500.0
4       205            5  2024-04-08        3500.0

In [13]:
#ordre_items

In [14]:
order_items_df = pd.read_sql("SELECT * FROM order_items", connection)
order_items_df.head()

C:\Users\daram\AppData\Local\Temp\ipykernel_36516\2650222213.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_items_df = pd.read_sql("SELECT * FROM order_items", connection)

   order_item_id  order_id  product_id  quantity    price
0            301       201         101         1   1200.0
1            302       202         102         1  55000.0
2            303       203         103         1    700.0
3            304       204         104         1   2500.0
4            305       205         105         1   3500.0

In [15]:
#basic check

In [16]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        15 non-null     int64
 1   customer_name      15 non-null     object
 2   email              15 non-null     object
 3   phone_number       15 non-null     object
 4   location           15 non-null     object
 5   registration_date  15 non-null     object
dtypes: int64(1), object(5)
memory usage: 852.0+ bytes

In [17]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    10 non-null     int64
 1   product_name  10 non-null     object
 2   category      10 non-null     object
 3   price         10 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [19]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     int64
 1   customer_id   10 non-null     int64
 2   order_date    10 non-null     object
 3   total_amount  10 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 452.0+ bytes

In [20]:
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  10 non-null     int64
 1   order_id       10 non-null     int64
 2   product_id     10 non-null     int64
 3   quantity       10 non-null     int64
 4   price          10 non-null     float64
dtypes: float64(1), int64(4)
memory usage: 532.0 bytes

In [21]:
#create dataset(combine all tables)

In [22]:
#orders+customers

In [23]:
df = pd.merge(orders_df, customers_df, on = "customer_id")

In [24]:
#add order items

In [25]:
df = pd.merge(df, order_items_df, on = "order_id")

In [26]:
#add products

In [28]:
df = pd.merge(df, products_df, on = "product_id")

In [29]:
df.head()

,order_id,customer_id,order_date,total_amount,customer_name,email,phone_number,location,registration_date,order_item_id,product_id,quantity,price_x,product_name,category,price_y
0,201,1,2024-04-01,1200.0,Kavya,kavya@gmail.com,9876543210,Hyderabad,2024-01-10,301,101,1,1200.0,Kurti,Clothing,1200.0
1,202,2,2024-04-03,55000.0,Ravi,ravi@gmail.com,9876543211,Chennai,2024-02-15,302,102,1,55000.0,Laptop,Electronics,55000.0
2,203,3,2024-04-04,700.0,Meena,meena@gmail.com,9876543212,Bangalore,2024-03-01,303,103,1,700.0,Lipstick,Beauty,700.0
3,204,4,2024-04-06,2500.0,Arjun,arjun@gmail.com,9876543213,Mumbai,2024-01-25,304,104,1,2500.0,Handbag,Accessories,2500.0
4,205,5,2024-04-08,3500.0,Sneha,sneha@gmail.com,9876543214,Delhi,2024-02-10,305,105,1,3500.0,Mixer Grinder,Home,3500.0

In [30]:
#total revenue

In [34]:
df.columns

Index(['order_id', 'customer_id', 'order_date', 'total_amount',
       'customer_name', 'email', 'phone_number', 'location',
       'registration_date', 'order_item_id', 'product_id', 'quantity',
       'price_x', 'product_name', 'category', 'price_y'],
      dtype='object')

In [37]:
df["total_revenue"] = df["quantity"] * df["price_x"]

In [38]:
df.head()

,order_id,customer_id,order_date,total_amount,customer_name,email,phone_number,location,registration_date,order_item_id,product_id,quantity,price_x,product_name,category,price_y,total_revenue
0,201,1,2024-04-01,1200.0,Kavya,kavya@gmail.com,9876543210,Hyderabad,2024-01-10,301,101,1,1200.0,Kurti,Clothing,1200.0,1200.0
1,202,2,2024-04-03,55000.0,Ravi,ravi@gmail.com,9876543211,Chennai,2024-02-15,302,102,1,55000.0,Laptop,Electronics,55000.0,55000.0
2,203,3,2024-04-04,700.0,Meena,meena@gmail.com,9876543212,Bangalore,2024-03-01,303,103,1,700.0,Lipstick,Beauty,700.0,700.0
3,204,4,2024-04-06,2500.0,Arjun,arjun@gmail.com,9876543213,Mumbai,2024-01-25,304,104,1,2500.0,Handbag,Accessories,2500.0,2500.0
4,205,5,2024-04-08,3500.0,Sneha,sneha@gmail.com,9876543214,Delhi,2024-02-10,305,105,1,3500.0,Mixer Grinder,Home,3500.0,3500.0

In [39]:
#analysis

In [40]:
#total_revenue

In [41]:
df["total_revenue"].sum()

np.float64(98800.0)

In [42]:
#top customers

In [43]:
df.groupby("customer_name")["total_revenue"].sum().sort_values(ascending=False)

customer_name
Ravi      55000.0
Anjali    20000.0
Kiran      7000.0
Vikram     5000.0
Sneha      3500.0
Rahul      3000.0
Arjun      2500.0
Kavya      1200.0
Priya       900.0
Meena       700.0
Name: total_revenue, dtype: float64

In [44]:
#sales by city

In [45]:
df.groupby("location")["total_revenue"].sum().sort_values(ascending=False)

location
Chennai      55900.0
Delhi        23500.0
Bangalore     7700.0
Hyderabad     6200.0
Pune          3000.0
Mumbai        2500.0
Name: total_revenue, dtype: float64

In [46]:
#best selling_products

In [48]:
df.groupby("product_name")["total_revenue"].sum().sort_values(ascending=False)

product_name
Laptop           55000.0
Smartphone       20000.0
Office Chair      7000.0
Watch             5000.0
Mixer Grinder     3500.0
Shoes             3000.0
Handbag           2500.0
Kurti             1200.0
Face Cream         900.0
Lipstick           700.0
Name: total_revenue, dtype: float64

In [49]:
#category wise sales

In [50]:
df.groupby("category")["total_revenue"].sum()

category
Accessories     7500.0
Beauty          1600.0
Clothing        1200.0
Electronics    75000.0
Fashion         3000.0
Furniture       7000.0
Home            3500.0
Name: total_revenue, dtype: float64

In [51]:
#save output

In [58]:
df.to_csv("final_dataset.csv",index=False)

In [53]:
#close conncetion

In [54]:
connection.close()

In [60]:
import os
os.getcwd()

'C:\\Users\\daram\\Downloads\\Py-DS-ML-Bootcamp-master\\Refactored_Py_DS_ML_Bootcamp-master\\01-Python-Crash-Course'

In [61]:
os.listdir()

['.ipynb_checkpoints',
 '01-Python Crash Course.ipynb',
 '02-Python Crash Course Exercises.ipynb',
 '03-Python Crash Course Exercises - Solutions.ipynb',
 'ecommerce_analysis.ipynb',
 'final_dataset.csv',
 'pandas.ipynb',
 'python.ipynb',
 'Untitled.ipynb']

In [63]:
import os
os.getlogin()

'daram'

In [65]:
df.to_csv("final_dataset.csv", index=False)

In [66]:
import os
os.getcwd()

'C:\\Users\\daram\\Downloads\\Py-DS-ML-Bootcamp-master\\Refactored_Py_DS_ML_Bootcamp-master\\01-Python-Crash-Course'